### ISSUE TITLE
[GitHub Action] .yml파일 내용구성

### ISSUE THREAD

**Issue by Kimsongbeen** [nhnacademy-aiot2-lucky7/study#2]
### github-actions-demo.yml파일 분석:

```
name: learn-github-actions
on:
    push:
      branches: [ master, dev ]
    pull_request:
      branches: [ master ]
      paths:
        - "**.js"
      paths-ignore:
        - "doc/**"
```
- name: 액션 탭에 노출되는 workflow의 이름(선택)
- push/pull_request 이벤트가 실행하는 시점마다 실행되게하는 설정
(특정 브랜치나, tag, path)

```
jobs:
  build:
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v2
        
      - name: My First Step
        run:
          npm install
          npm test
          npm build

      - name: Cache yarn dependencies 
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
```

- runs-on: 어떤 OS에서 실행할 것인지 명시
- steps: job이 가질 수 있는 동작의 나열
  - name: step 이름
  - uses: 해당 step에서 사용할 액션. {owner}/{repo}@{ref|version}의 형태
  - run: job에 할당된 컴퓨터 자원의 shell을 이용하여 command 라인 실행
- env: 해당 job에서 사용할 환경 변수를 key/value의 형태로 설정
- strategy: 여러 환경에서의 테스트/배포를 위해 빌드 matrix 구성
- with: 해당 action에 의해 정의되는 input parameter. key/value형태이며 input파라미터는 환경변수로 설정되고, 'INPUT_'이라는 prefix가 붙음

참고1: [https://velog.io/@ggong/Github-Action%EC%97%90-%EB%8C%80%ED%95%9C-%EC%86%8C%EA%B0%9C%EC%99%80-%EC%82%AC%EC%9A%A9%EB%B2%95](url)
참고2: [https://docs.github.com/en/actions/writing-workflows/quickstart](url)
